# Data Visualization Techniques

Data visualization is an important, and sometimes overlooked, aspect of social science. This week, we go back to the visualization techniques of Du Bois, which remind us that data science long predates the current era of ``big data." 

__Readings:__

* [Battle-Baptiste, Whitney; Rusert, Britt. 2018. Princeton Architectural Press. W. E. B. du Bois's Data Portraits : Visualizing Black America.](https://ebookcentral.proquest.com/lib/stanford-ebooks/detail.action?docID=5515147)

* [Data Visualization: A Practical Introduction. 5: Show the Right Numbers.](https://socviz.co/lookatdata.html#groupfacettx)

* [Data Visualization: A Practical Introduction. 6: Graph Tables, Add Labels, Make Notes.](https://socviz.co/lookatdata.html#workgeoms)

## Why Visualization?

We look at data for a reason. A well-designed visualization can make it easy to see important patterns and trends that might not pop out in tables. Visualization is also a good way to explore our data, or to look for potential issues or mistakes. 

W.E.B. Du Bois is credited with some of the most famous visualizations in the field of sociology. With researchers at Atlanta University, Du Bois communicated the state of Black Americans to the world at the 1906 Paris Exhibition through a series of graphs documenting racial the economic, social, and demogrpahic conditions of Black citizens. The purpose behind these plots made them impactful. But the artistic elements make them unforgettable.   


## Class Exercise

In this excercise, we are going to create our own visualizations using historical census data. In groups, answer the following: 

1. What are three ways that you could display the data? Describe the benefits and drawbacks of each. 

2. How will you display the data? What display elements will you add?

3. Sketch your data visualization. Be creative!




## Problem Set 3

1. Returning to the historical census data, re-create one of the visualizations from your classmates [you can find them here](). (You won't be penalized for not being able to fully replicate a chart).

2. What would you change in the visualization? Why? Modify and re-plot.



